---

- hosts: all
  become: true
  tasks:

  - name: remove apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
       - apache2
       - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove apache and php for CentOS servers
    tags: apache,httpd,centos
    dnf:
      name:
       - httpd
       - php
      state: absent
    when: ansible_distribution == "CentOS"
    
  - name: remove mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: absent
    when: ansible_distribution == "CentOS"
    
  - name: remove mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: absent
    when: ansible_distribution == "Ubuntu"
    
  - name: remove samba package (Ubuntu and CentOS)
    tags: samba
    package:
      name: samba
      state: absent